# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: RussMckendrick.Aicommit
PackageVersion: 0.0.10
PackageLocale: en-US
Publisher: Russ McKendrick
PublisherUrl: https://github.com/russmckendrick
PublisherSupportUrl: https://github.com/russmckendrick/aicommit/issues
PackageName: aicommit
PackageUrl: https://github.com/russmckendrick/aicommit
License: MIT
ShortDescription: A fast, opinionated CLI that generates Git commit messages and reviews staged diffs using AI. Written in Rust, installed as aic
Tags:
- ai-tools
- commit
- git
ReleaseNotes: 'Full Changelog: v0.0.9...v0.0.10'
ReleaseNotesUrl: https://github.com/russmckendrick/aicommit/releases/tag/v0.0.10
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/russmckendrick/aicommit/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
